# Generated by Django 5.1.3 on 2024-11-30 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paca', '0002_accesorio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesorio',
            old_name='tela',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='accesorio',
            name='talla',
        ),
    ]
