# Generated by Django 5.1.3 on 2024-11-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Electronico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prefijo', models.CharField(blank=True, choices=[('M', 'Mega'), ('k', 'Kilo'), ('', ''), ('m', 'Milli'), ('u', 'Micro'), ('n', 'Nano'), ('p', 'Pico')], max_length=1)),
                ('unidad', models.CharField(choices=[('Ω', 'Ohmios'), ('F', 'Faradios'), ('H', 'Henrios'), ('V', 'Voltios'), ('A', 'Amperios'), ('W', 'Vatios')], max_length=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
