# Generated by Django 5.1.3 on 2024-11-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronico',
            name='prefijo',
            field=models.CharField(blank=True, choices=[('M', 'Mega'), ('k', 'Kilo'), ('', ''), ('m', 'Milli'), ('μ', 'Micro'), ('n', 'Nano'), ('p', 'Pico')], max_length=1),
        ),
    ]
