# Generated by Django 5.1.3 on 2024-11-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronicos', '0002_alter_electronico_prefijo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronico',
            name='valor',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
